### ISSUE TITLE
error: The type name `Hdy.Flap' could not be found

### ISSUE THREAD

**Issue by yurivict** [lainsce/quilter#386]
Version 3.3.4 fails to compile on FreeBSD 12.2 with vala-0.48.10,1:
```
valac -C --target-glib=2.40 --pkg gtkspell3-3.0 --pkg webkit2gtk-4.0 --pkg gtksourceview-4 --pkg libhandy-1 --pkg gee-0.8 --pkg gobject-2.0 --pkg glib-2.0 --pkg gtk+-3.0 --pkg gio-2.0 --color=always --directory io.github.lainsce.Quilter.p --basedir ../ --gresources=../data/app.gresource.xml /usr/ports/editors/quilter/work/quilter-3.3.4/vapi/libmarkdown.vapi /usr/ports/editors/quilter/work/quilter-3.3.4/src/Config.vapi ../src/Application.vala ../src/MainWindow.vala ../src/Widgets/HeaderBar.vala ../src/Widgets/HeaderBarButton.vala ../src/Widgets/SourceView.vala ../src/Widgets/WebView.vala ../src/Widgets/SearchBar.vala ../src/Widgets/StatusBar.vala ../src/Widgets/SideBar.vala ../src/Widgets/SideBarBox.vala ../src/Widgets/Preferences.vala ../src/Plugins/PluginManager.vala ../src/Plugins/Plugin.vala ../src/Plugins/Image.vala ../src/Plugins/Filep.vala ../src/Plugins/Checkbox.vala ../src/Plugins/CheckboxChecked.vala ../src/Plugins/Highlighter.vala ../src/Plugins/Superscript.vala ../src/Plugins/Subscript.vala ../src/Styles/quilter.vala ../src/Styles/quilterdark.vala ../src/Styles/quiltersepia.vala ../src/Constants/AppSettings.vala ../src/Services/FileManager.vala ../src/Services/ExportUtils.vala ../src/Services/DialogUtils.vala
../src/Widgets/SideBar.vala:40.16-40.23: error: The type name `Hdy.Flap' could not be found
        public Hdy.Flap flap;
               ^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
```

configure succeeded:
```
The Meson build system
Version: 0.57.1
Source dir: /usr/ports/editors/quilter/work/quilter-3.3.4
Build dir: /usr/ports/editors/quilter/work/quilter-3.3.4/_build
Build type: native build
Project name: io.github.lainsce.Quilter
Project version: 3.3.0
C compiler for the host machine: cc (clang 10.0.1 "FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)")
C linker for the host machine: cc ld.lld 10.0.1
Vala compiler for the host machine: valac (valac 0.48.10)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h using configuration
Found pkg-config: /usr/local/bin/pkgconf (1.7.4)
Program glib-compile-resources found: YES (/usr/local/bin/glib-compile-resources)
Library markdown found: YES
Found pkg-config: /usr/local/bin/pkgconf (1.7.4)
Run-time dependency gio-2.0 found: YES 2.66.7
Run-time dependency gtk+-3.0 found: YES 3.24.24
Run-time dependency glib-2.0 found: YES 2.66.7
Run-time dependency gobject-2.0 found: YES 2.66.7
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency libhandy-1 found: YES 1.0.3
Run-time dependency gtksourceview-4 found: YES 4.8.0
Run-time dependency webkit2gtk-4.0 found: YES 2.30.5
Run-time dependency gtkspell3-3.0 found: YES 3.0.10
Dependency libhandy-1 found: YES 1.0.3 (cached)
Library m found: YES
Program msgfmt found: YES (/usr/local/bin/msgfmt)
Configuring io.github.lainsce.Quilter.desktop.desktop.in using configuration
Program desktop-file-validate found: YES (/usr/local/bin/desktop-file-validate)
Program glib-compile-resources found: YES (/usr/local/bin/glib-compile-resources)
Program build-aux/post_install.py found: YES (/usr/local/bin/python3.7 /usr/ports/editors/quilter/work/quilter-3.3.4/build-aux/post_install.py)
Build targets in project: 12
```

**Comment by lainsce** [comment]
If you get an updated libhandy pkg, you'll get Hdy.Flap.
