### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by nick87720z** [lainsce/quilter#123]
Since last change is nearly 16 days ago, i decided it is worth to report.
I got update to faedc36. It fails to build with both vala-0.34 and 0.36.

Build log (vala-0.34): https://gist.github.com/nick87720z/8f59825d3789dd1525f524f4830faf3b

**Comment by lainsce** [comment]
This looks like you forgot to install Granite to me. Try installing it and see if the compilation succeeds? 😄

**Comment by nick87720z** [comment]
Yeah, i simply missed granite update :)
Latest packaged version is still 0.4.1 :/

**Comment by lainsce** [comment]
Well, all of my apps move forward with libraries, such that if granite has version 6 tomorrow, my apps would already be using it. Maybe bug your distro packagers with a new version for granite?

**Comment by nick87720z** [comment]
Yep, i just bumped version in local overlay)
For now most recent (0.4.1) granite presents in elementary overlay, but its maintainer doesn't seem to have time to do it as much as elementary team does with their deb ppa.
